### ISSUE TITLE
Servohalter/Heilbronn ist krumm. Soll das so sein? :)

### ISSUE THREAD

**Issue by freaky-m0** [hiveeyes/hani-mandl#28]
Hi,

ist mir nur aufgefallen, weil ich es zu dieser Seite auf dem Druckbett ausgerichtet hatte. Ist irgendwie krumm der Servohalter von der Heilbronn Variante. Soll das so sein? Ist das erste Mal, dass ich den Bausatz drucke. (Die Pfeile sind zur Verdeutlichung)

![grafik](https://user-images.githubusercontent.com/4473764/115827735-ff9d6500-a40c-11eb-85cc-df7e55813ac5.png)

Danke & Gruß

**Comment by MKO1640** [comment]
Sollte eigentlich nicht so sein, es macht schon Sinn, ihn in dieser Ausrichtung zu drucken. Bei nicht perfekter Layerhaftung würde er sonnst leichter brechen. 
Da ich ihn nicht konstruiert habe kann ich leider nichts zu den Beweggründen sagen. Es ist ja etwas aufwendiger den Halter mit der Schrägung zu Konstruieren, denke es gibt da schon einen Grund.

**Comment by amotl** [comment]
Hallo @freaky-m0,

wahrscheinlich werden wir nicht mehr herausfinden, warum das Bauelement so konstruiert wurde, aber ggf. kann der ursprüngliche Autor hier noch antworten. Einstweilen schließe ich das Ticket, but feel free to re-open if applicable.

Viele Grüße,
Andreas.
